name: Demo Docker

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/website-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Login GHCR
      - name: Login to GHCR
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      # Push image
      - name: Push image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }}

            docker pull $IMAGE_NAME:latest

            docker stop website-demo || true
            docker rm website-demo || true

            docker run -d \
              --name website-demo \
              -p 80:80 \
              --restart always \
              $IMAGE_NAME:latest
